export const productsData = [
  {
    id: 'raspberry_jam',
    name: 'Raspberry Jam',
    subtitle: 'Marmellata di Lamponi • مربى التوت',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Star of Commercial',
    image: '/products/raspberry_jam.png',
    accentColor: '#c0392b',
    gradient: 'linear-gradient(135deg, #c0392b 0%, #8e181b 100%)',
    videoTimestamp: 2.0,
    tagline: 'Fresh Ripe Raspberries Transformed into Pure Indulgence',
    description: 'Featured in the commercial! Ahmed Foods Raspberry Jam is crafted using handpicked, succulent wild raspberries. Every spoonful delivers a delicate balance of tart sweetness and rich aromatic fruit pulp.',
    flavorProfile: ['Sweet & Tangy', 'Floral Berry Aroma', 'Velvety Pulp Texture'],
    ingredients: ['Ripe Raspberries (45%)', 'Pure Cane Sugar', 'Fruit Pectin', 'Citric Acid'],
    nutrition: {
      energy: '260 kcal / 100g',
      fruitContent: '45% Real Fruit',
      sugars: '62g',
      fat: '0g',
      vitaminC: 'High in Vitamin C'
    },
    pairing: 'Warm croissants, sourdough toast, Belgian waffles, Greek yogurt, or cheesecake glaze.'
  },
  {
    id: 'strawberry_jam',
    name: 'Strawberry Jam',
    subtitle: 'Marmellata di Fragole • مربى الفراولة',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Global Best-Seller',
    image: '/products/strawberry_jam.png',
    accentColor: '#e74c3c',
    gradient: 'linear-gradient(135deg, #e74c3c 0%, #961b1b 100%)',
    videoTimestamp: 8.5,
    tagline: 'Sun-Drenched Garden Strawberries in Every Spoon',
    description: 'Ahmed Foods Strawberry Jam is a beloved breakfast icon across the globe. Made from farm-fresh, sweet strawberries carefully simmered to preserve their ruby color and juicy mouthfeel.',
    flavorProfile: ['Lush Berry Sweetness', 'Rich Red Hue', 'Generous Fruit Bits'],
    ingredients: ['Selected Strawberries (45%)', 'Sugar', 'Gelling Agent (Pectin)', 'Citric Acid'],
    nutrition: {
      energy: '258 kcal / 100g',
      fruitContent: '45% Real Fruit',
      sugars: '61g',
      fat: '0g',
      vitaminC: 'Antioxidant Rich'
    },
    pairing: 'Buttered English muffins, fresh scones with clotted cream, or folded into vanilla ice cream.'
  },
  {
    id: 'mixed_fruit_jam',
    name: 'Mixed Fruit Jam',
    subtitle: 'Marmellata di Frutta Mista • مربى فواكة مشكلة',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Signature Heritage Recipe',
    image: '/products/mixed_fruit_jam.png',
    accentColor: '#e67e22',
    gradient: 'linear-gradient(135deg, #e67e22 0%, #b35309 100%)',
    videoTimestamp: 9.0,
    tagline: 'A Masterful Symphony of Farm-Fresh Orchard Fruits',
    description: 'The crowning jewel of the Ahmed Foods line since 1952. A harmonious blend of apples, grapes, mangoes, pineapples, and seasonal berries that has nourished families for generations.',
    flavorProfile: ['Multi-Fruit Complexity', 'Warm Tropical Finish', 'Smooth Spreadability'],
    ingredients: ['Fruit Medley (Apple, Mango, Papaya, Pineapple, Grapes) (45%)', 'Sugar', 'Pectin', 'Acidity Regulator'],
    nutrition: {
      energy: '265 kcal / 100g',
      fruitContent: '45% Multi-Fruit Blend',
      sugars: '63g',
      fat: '0g',
      vitaminC: 'Multi-Vitamin Enriched'
    },
    pairing: 'Classic toasted brioche, afternoon tea biscuits, and family breakfast sandwiches.'
  },
  {
    id: 'orange_marmalade',
    name: 'Orange Marmalade',
    subtitle: 'Marmellata di Arance • مربى البرتقال',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Zesty & Refreshing',
    image: '/products/orange_marmalade.png',
    accentColor: '#f39c12',
    gradient: 'linear-gradient(135deg, #f39c12 0%, #b76a06 100%)',
    videoTimestamp: 8.8,
    tagline: 'Golden Citrus Sunshine with Tender Shreds of Orange Rind',
    description: 'Awaken your palate with classic Seville oranges. The subtle bitterness of citrus zest perfectly balances natural fruit sugars for an invigorating morning wake-up.',
    flavorProfile: ['Citrus Tang', 'Subtle Aromatic Bitters', 'Translucent Amber Jelly'],
    ingredients: ['Oranges & Orange Shreds (40%)', 'Sugar', 'Citrus Pectin', 'Citric Acid'],
    nutrition: {
      energy: '252 kcal / 100g',
      fruitContent: '40% Real Citrus',
      sugars: '60g',
      fat: '0g',
      vitaminC: 'High Vitamin C'
    },
    pairing: 'Crispy dark rye toast, glazed roasted poultry, charcuterie boards with sharp cheddar.'
  },
  {
    id: 'blueberry_jam',
    name: 'Blueberry Jam',
    subtitle: 'Marmellata di Mirtilli • مربى التوت الأزرق',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Superfood Indulgence',
    image: '/products/blueberry_jam.png',
    accentColor: '#2980b9',
    gradient: 'linear-gradient(135deg, #2980b9 0%, #154360 100%)',
    videoTimestamp: 9.1,
    tagline: 'Plump Wild Blueberries Rich in Anthocyanin Antioxidants',
    description: 'Filled with plump, tender blueberries harvested at the peak of sweetness. Gives a deep indigo spread that turns oatmeal and pancakes into a luxury gourmet treat.',
    flavorProfile: ['Earthy Wild Berry', 'Deep Indigo Tone', 'Silky Smooth Finish'],
    ingredients: ['Wild Blueberries (45%)', 'Pure Sugar', 'Pectin', 'Acidity Regulator'],
    nutrition: {
      energy: '255 kcal / 100g',
      fruitContent: '45% Wild Blueberries',
      sugars: '61g',
      fat: '0g',
      vitaminC: 'Potent Anthocyanin Antioxidants'
    },
    pairing: 'Fluffy buttermilk pancakes, chia pudding bowls, crepes, and mascarpone tart.'
  },
  {
    id: 'blackcurrant_jam',
    name: 'Blackcurrant Jam',
    subtitle: 'Marmellata di Ribes Nero • مربى الكشمش الأسود',
    netWeight: '450g (15.87 Oz.)',
    badge: 'European Classic',
    image: '/products/blackcurrant_jam.png',
    accentColor: '#4a235a',
    gradient: 'linear-gradient(135deg, #6c3483 0%, #2e1044 100%)',
    videoTimestamp: 8.9,
    tagline: 'Deep, Robust Tartness Loved by Connoisseurs',
    description: 'Blackcurrants have four times the vitamin C of oranges. Ahmed Foods Blackcurrant Jam preserves the full-bodied, slightly musky and sharp taste that makes every bite memorable.',
    flavorProfile: ['Intense Tart-Sweet', 'Royal Purple Hue', 'Full-Bodied Body'],
    ingredients: ['Blackcurrants (45%)', 'Sugar', 'Natural Pectin', 'Citric Acid'],
    nutrition: {
      energy: '250 kcal / 100g',
      fruitContent: '45% Whole Blackcurrants',
      sugars: '60g',
      fat: '0g',
      vitaminC: 'Ultra High Vitamin C'
    },
    pairing: 'Crumpets, artisanal sourdough, dark chocolate cake glaze, roasted lamb reductions.'
  },
  {
    id: 'pineapple_jam',
    name: 'Pineapple Jam',
    subtitle: 'Marmellata di Ananas • مربى الأناناس',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Tropical Selection',
    image: '/products/pineapple_jam.png',
    accentColor: '#f1c40f',
    gradient: 'linear-gradient(135deg, #f1c40f 0%, #b7950b 100%)',
    videoTimestamp: 8.7,
    tagline: 'Juicy Golden Pineapples with an Exotic Island Twist',
    description: 'Brimming with golden pineapple pulp, this conserve delivers an authentic tropical escapade. Smooth, bright, and invigoratingly sweet.',
    flavorProfile: ['Zingy Tropical Sweetness', 'Golden Sunny Tint', 'Fresh Fruit Fiber'],
    ingredients: ['Selected Pineapples (45%)', 'Sugar', 'Pectin', 'Citric Acid'],
    nutrition: {
      energy: '254 kcal / 100g',
      fruitContent: '45% Fresh Pineapple',
      sugars: '61g',
      fat: '0g',
      vitaminC: 'Natural Bromelain Enzyme'
    },
    pairing: 'Coconut French toast, upside-down cake filling, Danish pastries, cheese platters.'
  },
  {
    id: 'apple_jam',
    name: 'Apple Jam',
    subtitle: 'Marmellata di Mele • مربى التفاح',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Orchard Harvest',
    image: '/products/apple_jam.png',
    accentColor: '#27ae60',
    gradient: 'linear-gradient(135deg, #27ae60 0%, #196f3d 100%)',
    videoTimestamp: 9.2,
    tagline: 'Gentle Orchard Apples Stewed to Velvety Comfort',
    description: 'Made from crisp mountain apples simmered slowly until they turn into a translucent golden honey-like conserve. Mild, comforting, and perfect for all ages.',
    flavorProfile: ['Warm Orchard Sweetness', 'Delicate Autumn Note', 'Melt-in-Mouth Smoothness'],
    ingredients: ['Crisp Apples (45%)', 'Sugar', 'Apple Pectin', 'Citric Acid'],
    nutrition: {
      energy: '250 kcal / 100g',
      fruitContent: '45% Real Apple',
      sugars: '59g',
      fat: '0g',
      vitaminC: 'Gentle Pectin-Rich Fiber'
    },
    pairing: 'Warm cinnamon rolls, oatmeal, Dutch apple strudel, aged Gouda.'
  },
  {
    id: 'apricot_jam',
    name: 'Apricot Jam',
    subtitle: 'Marmellata di Albicocche • مربى المشمش',
    netWeight: '450g (15.87 Oz.)',
    badge: 'Golden Preserve',
    image: '/products/apricot_jam.png',
    accentColor: '#d35400',
    gradient: 'linear-gradient(135deg, #d35400 0%, #873600 100%)',
    videoTimestamp: 9.3,
    tagline: 'Velvety Sun-Drenched Apricots with Aromatic Floral Honey Notes',
    description: 'Prized by bakers and pastry chefs worldwide for its rich golden sheen, smooth melting consistency, and heavenly apricot bouquet.',
    flavorProfile: ['Honeyed Apricot Nectar', 'Silky Glaze Texture', 'Delicate Acidity'],
    ingredients: ['Sun-Ripened Apricots (45%)', 'Sugar', 'Pectin', 'Acidity Regulator'],
    nutrition: {
      energy: '256 kcal / 100g',
      fruitContent: '45% Sun-Ripened Apricots',
      sugars: '60g',
      fat: '0g',
      vitaminC: 'Rich in Vitamin A'
    },
    pairing: 'Sachertorte glaze, Danish pastries, almond croissants, morning toast.'
  }
];
